webtalk_init -webtalk_dir C:/Users/YaKerTaker/Google Drive/8vo/Arquitectura-Computadoras/Practica7/MemDatos/MemDatos.sim/sim_1/synth/func/xsim/xsim.dir/test_bench_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr  5 21:50:30 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3da67f73-46f6-475c-9200-73a49d3b0747" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "09589d4c229e4f24b8a7e740cb7e27f0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "163" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "24" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "199 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "40 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1045" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "243" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.69_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "106636_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1799829417 -regid "" -xml C:/Users/YaKerTaker/Google Drive/8vo/Arquitectura-Computadoras/Practica7/MemDatos/MemDatos.sim/sim_1/synth/func/xsim/xsim.dir/test_bench_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/YaKerTaker/Google Drive/8vo/Arquitectura-Computadoras/Practica7/MemDatos/MemDatos.sim/sim_1/synth/func/xsim/xsim.dir/test_bench_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/YaKerTaker/Google Drive/8vo/Arquitectura-Computadoras/Practica7/MemDatos/MemDatos.sim/sim_1/synth/func/xsim/xsim.dir/test_bench_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
